title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://abhishekraj007.github.io/blogs
baseurl: ""
paginate_path: "blogs/page:num/"
permalink: blogs/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
